[providers]
node = "18"

[phases.setup]
aptPkgs = ["wget", "gnupg", "ca-certificates"]

[phases.install]
cmds = [
  # Update packages first
  "apt-get update -y",
  
  # Install ALL dependencies from GitHub issue solutions
  "apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils",
  
  # Additional dependencies from GitHub solutions
  "apt-get install -y gconf-service libgconf-2-4 libgdk-pixbuf2.0-0 libappindicator1",
  
  # Extra dependencies mentioned in comments
  "apt-get install -y libxkbcommon0 libxdamage-dev libdrm2 libxcomposite1 libxrandr2",
  
  # Install Chrome
  "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'",
  "apt-get update",
  "apt-get install -y google-chrome-stable",
  
  # Clean up to reduce image size
  "rm -rf /var/lib/apt/lists/*",
  
  # Install Node dependencies
  "npm install"
]

[start]
cmd = "npm start"